### PR TITLE
Release v1

### PR DESCRIPTION
**Pull request by srevinsaju**
@quozl Please review.

### CODE REVIEW

**Comment by quozl** [comment]
Looks fine to me.

**Comment by srevinsaju** [comment]
@quozl What about the POT files? How can it be translated?

**Comment by quozl** [comment]
Get the project onto translate.sugarlabs.org.  I don't know how, sorry.  I think we have lost a volunteer.

You might also preload translations using other projects.  For instance on Pippy when I [Add(ed a) notebook tab close confirmation alert](https://github.com/sugarlabs/Pippy/commit/bb1aa91ae843e1b2d01fe663c0ebfbd6a4485cfd) I wrote a quick hack with polib to borrow "Erase" translations from Sugar.

```python
#!/usr/bin/python3

import polib
import os
import sys
import glob

print("read potfile")
potf = polib.pofile('po/Pippy.pot')

print("read mine")
mine = {}
for name in glob.glob('po/*.po'):
    base = os.path.basename(name)
    mine[base] = polib.pofile(name)

print("read hers")
hers = {}
for name in glob.glob('../sugar/po/*.po'):
    base = os.path.basename(name)
    hers[base] = polib.pofile(name)

print("think")
for entry in potf:
    if 'rase' not in entry.msgid:  # new erase messages
        continue
    print(entry)

    for base in sorted(mine.keys()):  # each language
        print(base)
        find = mine[base].find(entry.msgid)
        if find is not None:
            print("  is already in my %r" % base)
        else:
            print("  is not in my %r" % base)
            if base in hers:
                alt = hers[base].find(entry.msgid)
                if alt is None:
                    print("    is not in hers, ignore")
                    continue
                if alt.msgstr == alt.msgid:
                    print("    is in hers but untranslated, ignore")
                    continue
                if alt.msgstr == '':
                    print("    is in hers but empty string, ignore")
                    continue
                print("    use %r" % alt.msgstr)

                new = entry
                new.msgstr = alt.msgstr
                fp = open('po/%s' % base, 'a')
                print("", file=fp)
                print(new, file=fp)
                fp.close()
```

**Comment by srevinsaju** [comment]
I guess, I shall add the translations in a next release

**Pull request merged**
